# MSBuild properties that correspond to cl.exe and link.exe switches.
#
# A recognized switch is removed from AdditionalOptions and set as its property
# instead. The tables are Visual Studio's own switch definitions as CMake
# extracts them, plus /std:c++23 and the "/D name" and "/I dir" forms CMake also
# accepts. They are matched the way CMake matches them: a switch may start with
# '-' or '/'; entries are tried in order; a fixed switch matches exactly; a VALUE
# switch matches by prefix and takes the rest as its value (optional when the
# value is IGNORED); a FOLLOWING switch takes the next argument; LIST properties
# accumulate with ';'; and a CONTINUE entry lets later entries match the same
# switch.

from enum import Flag
from typing import Dict, List, Optional, Tuple


class Arg(Flag):
    FIXED = 0
    VALUE = 1  # the switch is followed by the user's value: /wd4100
    FOLLOWING = 2  # the user's value is the next argument: /FI x.h
    IGNORED = 4  # the value is optional and the property gets the entry's value
    CONTINUE = 8  # later entries may also match the switch
    LIST = 16  # values accumulate, separated by ';'
    CASE_INSENSITIVE = 32


Switch = Tuple[str, str, Optional[str], Arg]

# Switches each toolset defines. TOOLSET_SWITCHES names the entries only some
# toolsets define; every other entry applies to all of them.
CL_SWITCHES = [
    ("/Z7", "DebugInformationFormat", "OldStyle", Arg.FIXED),
    ("/Zi", "DebugInformationFormat", "ProgramDatabase", Arg.FIXED),
    ("/ZI", "DebugInformationFormat", "EditAndContinue", Arg.FIXED),
    ("/clr", "CompileAsManaged", "true", Arg.FIXED),
    ("/clr:pure", "CompileAsManaged", "Pure", Arg.FIXED),
    ("/clr:safe", "CompileAsManaged", "Safe", Arg.FIXED),
    ("/clr:netcore", "CLRSupport", "NetCore", Arg.FIXED),
    ("/W0", "WarningLevel", "TurnOffAllWarnings", Arg.FIXED),
    ("/W1", "WarningLevel", "Level1", Arg.FIXED),
    ("/W2", "WarningLevel", "Level2", Arg.FIXED),
    ("/W3", "WarningLevel", "Level3", Arg.FIXED),
    ("/W4", "WarningLevel", "Level4", Arg.FIXED),
    ("/Wall", "WarningLevel", "EnableAllWarnings", Arg.FIXED),
    ("/diagnostics:caret", "DiagnosticsFormat", "Caret", Arg.FIXED),
    ("/diagnostics:column", "DiagnosticsFormat", "Column", Arg.FIXED),
    ("/diagnostics:classic", "DiagnosticsFormat", "Classic", Arg.FIXED),
    ("/Od", "Optimization", "Disabled", Arg.FIXED),
    ("/O1", "Optimization", "MinSpace", Arg.FIXED),
    ("/O2", "Optimization", "MaxSpeed", Arg.FIXED),
    ("/Ox", "Optimization", "Full", Arg.FIXED),
    ("/Ob0", "InlineFunctionExpansion", "Disabled", Arg.FIXED),
    ("/Ob1", "InlineFunctionExpansion", "OnlyExplicitInline", Arg.FIXED),
    ("/Ob2", "InlineFunctionExpansion", "AnySuitable", Arg.FIXED),
    ("/Os", "FavorSizeOrSpeed", "Size", Arg.FIXED),
    ("/Ot", "FavorSizeOrSpeed", "Speed", Arg.FIXED),
    ("/EHa", "ExceptionHandling", "Async", Arg.FIXED),
    ("/EHsc", "ExceptionHandling", "Sync", Arg.FIXED),
    ("/EHs", "ExceptionHandling", "SyncCThrow", Arg.FIXED),
    ("/RTCs", "BasicRuntimeChecks", "StackFrameRuntimeCheck", Arg.FIXED),
    ("/RTCu", "BasicRuntimeChecks", "UninitializedLocalUsageCheck", Arg.FIXED),
    ("/RTC1", "BasicRuntimeChecks", "EnableFastChecks", Arg.FIXED),
    ("/MT", "RuntimeLibrary", "MultiThreaded", Arg.FIXED),
    ("/MTd", "RuntimeLibrary", "MultiThreadedDebug", Arg.FIXED),
    ("/MD", "RuntimeLibrary", "MultiThreadedDLL", Arg.FIXED),
    ("/MDd", "RuntimeLibrary", "MultiThreadedDebugDLL", Arg.FIXED),
    ("/Zp1", "StructMemberAlignment", "1Byte", Arg.FIXED),
    ("/Zp2", "StructMemberAlignment", "2Bytes", Arg.FIXED),
    ("/Zp4", "StructMemberAlignment", "4Bytes", Arg.FIXED),
    ("/Zp8", "StructMemberAlignment", "8Bytes", Arg.FIXED),
    ("/Zp16", "StructMemberAlignment", "16Bytes", Arg.FIXED),
    ("/GS-", "BufferSecurityCheck", "false", Arg.FIXED),
    ("/GS", "BufferSecurityCheck", "true", Arg.FIXED),
    ("/guard:cf", "ControlFlowGuard", "Guard", Arg.FIXED),
    ("/arch:SSE", "EnableEnhancedInstructionSet", "StreamingSIMDExtensions", Arg.FIXED),
    (
        "/arch:SSE2",
        "EnableEnhancedInstructionSet",
        "StreamingSIMDExtensions2",
        Arg.FIXED,
    ),
    (
        "/arch:AVX",
        "EnableEnhancedInstructionSet",
        "AdvancedVectorExtensions",
        Arg.FIXED,
    ),
    (
        "/arch:AVX2",
        "EnableEnhancedInstructionSet",
        "AdvancedVectorExtensions2",
        Arg.FIXED,
    ),
    (
        "/arch:AVX512",
        "EnableEnhancedInstructionSet",
        "AdvancedVectorExtensions512",
        Arg.FIXED,
    ),
    (
        "/arch:AVX10.1",
        "EnableEnhancedInstructionSet",
        "AdvancedVectorExtensions101",
        Arg.FIXED,
    ),
    (
        "/arch:AVX10.2",
        "EnableEnhancedInstructionSet",
        "AdvancedVectorExtensions102",
        Arg.FIXED,
    ),
    (
        "/arch:ARMv7VE",
        "EnableEnhancedInstructionSet",
        "VirtualizationExtensions",
        Arg.FIXED,
    ),
    ("/arch:VFPv4", "EnableEnhancedInstructionSet", "ARMVFPv4Instructions", Arg.FIXED),
    (
        "/arch:armv8.0",
        "EnableEnhancedInstructionSet",
        "CPUExtensionRequirementsARMv80",
        Arg.FIXED,
    ),
    (
        "/arch:armv8.1",
        "EnableEnhancedInstructionSet",
        "CPUExtensionRequirementsARMv81",
        Arg.FIXED,
    ),
    (
        "/arch:armv8.2",
        "EnableEnhancedInstructionSet",
        "CPUExtensionRequirementsARMv82",
        Arg.FIXED,
    ),
    (
        "/arch:armv8.3",
        "EnableEnhancedInstructionSet",
        "CPUExtensionRequirementsARMv83",
        Arg.FIXED,
    ),
    (
        "/arch:armv8.4",
        "EnableEnhancedInstructionSet",
        "CPUExtensionRequirementsARMv84",
        Arg.FIXED,
    ),
    (
        "/arch:armv8.5",
        "EnableEnhancedInstructionSet",
        "CPUExtensionRequirementsARMv85",
        Arg.FIXED,
    ),
    (
        "/arch:armv8.6",
        "EnableEnhancedInstructionSet",
        "CPUExtensionRequirementsARMv86",
        Arg.FIXED,
    ),
    (
        "/arch:armv8.7",
        "EnableEnhancedInstructionSet",
        "CPUExtensionRequirementsARMv87",
        Arg.FIXED,
    ),
    (
        "/arch:armv8.8",
        "EnableEnhancedInstructionSet",
        "CPUExtensionRequirementsARMv88",
        Arg.FIXED,
    ),
    ("/arch:IA32", "EnableEnhancedInstructionSet", "NoExtensions", Arg.FIXED),
    ("/arch:NotSet", "EnableEnhancedInstructionSet", "NotSet", Arg.FIXED),
    ("/vlen=256", "EnableVectorLength", "VectorLength256", Arg.FIXED),
    ("/vlen=512", "EnableVectorLength", "VectorLength512", Arg.FIXED),
    ("/fp:precise", "FloatingPointModel", "Precise", Arg.FIXED),
    ("/fp:strict", "FloatingPointModel", "Strict", Arg.FIXED),
    ("/fp:fast", "FloatingPointModel", "Fast", Arg.FIXED),
    ("/Qspectre-load-cf", "SpectreMitigation", "SpectreLoadCF", Arg.FIXED),
    ("/Qspectre-load", "SpectreMitigation", "SpectreLoad", Arg.FIXED),
    ("/Qspectre-", "SpectreMitigation", "false", Arg.FIXED),
    ("/Qspectre", "SpectreMitigation", "Spectre", Arg.FIXED),
    ("/std:c++14", "LanguageStandard", "stdcpp14", Arg.FIXED),
    ("/std:c++17", "LanguageStandard", "stdcpp17", Arg.FIXED),
    ("/std:c++20", "LanguageStandard", "stdcpp20", Arg.FIXED),
    ("/std:c++23preview", "LanguageStandard", "stdcpp23", Arg.FIXED),
    ("/std:c++23", "LanguageStandard", "stdcpp23", Arg.FIXED),
    ("/std:c++latest", "LanguageStandard", "stdcpplatest", Arg.FIXED),
    ("/std:c11", "LanguageStandard_C", "stdc11", Arg.FIXED),
    ("/std:c17", "LanguageStandard_C", "stdc17", Arg.FIXED),
    ("/std:clatest", "LanguageStandard_C", "stdclatest", Arg.FIXED),
    ("/permissive-", "ConformanceMode", "true", Arg.FIXED),
    ("/permissive", "ConformanceMode", "false", Arg.FIXED),
    ("/Yc", "PrecompiledHeader", "Create", Arg.VALUE | Arg.IGNORED | Arg.CONTINUE),
    ("/Yu", "PrecompiledHeader", "Use", Arg.VALUE | Arg.IGNORED | Arg.CONTINUE),
    ("/Y-", "PrecompiledHeader", "NotUsing", Arg.FIXED),
    ("/FA", "AssemblerOutput", "AssemblyCode", Arg.FIXED),
    ("/FAc", "AssemblerOutput", "AssemblyAndMachineCode", Arg.FIXED),
    ("/FAs", "AssemblerOutput", "AssemblyAndSourceCode", Arg.FIXED),
    ("/FAcs", "AssemblerOutput", "All", Arg.FIXED),
    ("/external:W0", "ExternalWarningLevel", "TurnOffAllWarnings", Arg.FIXED),
    ("/external:W1", "ExternalWarningLevel", "Level1", Arg.FIXED),
    ("/external:W2", "ExternalWarningLevel", "Level2", Arg.FIXED),
    ("/external:W3", "ExternalWarningLevel", "Level3", Arg.FIXED),
    ("/external:W4", "ExternalWarningLevel", "Level4", Arg.FIXED),
    ("/Gd", "CallingConvention", "Cdecl", Arg.FIXED),
    ("/Gr", "CallingConvention", "FastCall", Arg.FIXED),
    ("/Gz", "CallingConvention", "StdCall", Arg.FIXED),
    ("/Gv", "CallingConvention", "VectorCall", Arg.FIXED),
    ("/TC", "CompileAs", "CompileAsC", Arg.FIXED),
    ("/TP", "CompileAs", "CompileAsCpp", Arg.FIXED),
    ("/errorReport:none", "ErrorReporting", "None", Arg.FIXED),
    ("/errorReport:prompt", "ErrorReporting", "Prompt", Arg.FIXED),
    ("/errorReport:queue", "ErrorReporting", "Queue", Arg.FIXED),
    ("/errorReport:send", "ErrorReporting", "Send", Arg.FIXED),
    ("/translateInclude", "TranslateIncludes", "true", Arg.FIXED),
    ("/JMC-", "SupportJustMyCode", "false", Arg.FIXED),
    ("/JMC", "SupportJustMyCode", "true", Arg.FIXED),
    ("/ZW", "CompileAsWinRT", "true", Arg.FIXED),
    ("/ZW:nostdlib", "WinRTNoStdLib", "true", Arg.FIXED),
    ("/nologo", "SuppressStartupBanner", "true", Arg.FIXED),
    ("/WX-", "TreatWarningAsError", "false", Arg.FIXED),
    ("/WX", "TreatWarningAsError", "true", Arg.FIXED),
    ("/sdl-", "SDLCheck", "false", Arg.FIXED),
    ("/sdl", "SDLCheck", "true", Arg.FIXED),
    (
        "/MP",
        "MultiProcessorCompilation",
        "true",
        Arg.VALUE | Arg.IGNORED | Arg.CONTINUE,
    ),
    ("/Oi", "IntrinsicFunctions", "true", Arg.FIXED),
    ("/Oy-", "OmitFramePointers", "false", Arg.FIXED),
    ("/Oy", "OmitFramePointers", "true", Arg.FIXED),
    ("/GT", "EnableFiberSafeOptimizations", "true", Arg.FIXED),
    ("/GL", "WholeProgramOptimization", "true", Arg.FIXED),
    ("/u", "UndefineAllPreprocessorDefinitions", "true", Arg.FIXED),
    ("/X", "IgnoreStandardIncludePath", "true", Arg.FIXED),
    ("/P", "PreprocessToFile", "true", Arg.FIXED),
    ("/EP", "PreprocessSuppressLineNumbers", "true", Arg.FIXED),
    ("/C", "PreprocessKeepComments", "true", Arg.FIXED),
    ("/Zc:preprocessor-", "UseStandardPreprocessor", "false", Arg.FIXED),
    ("/Zc:preprocessor", "UseStandardPreprocessor", "true", Arg.FIXED),
    ("/GF-", "StringPooling", "false", Arg.FIXED),
    ("/GF", "StringPooling", "true", Arg.FIXED),
    ("/Gm-", "MinimalRebuild", "false", Arg.FIXED),
    ("/Gm", "MinimalRebuild", "true", Arg.FIXED),
    ("/RTCc", "SmallerTypeCheck", "true", Arg.FIXED),
    ("/Gy-", "FunctionLevelLinking", "false", Arg.FIXED),
    ("/Gy", "FunctionLevelLinking", "true", Arg.FIXED),
    ("/Qpar-", "EnableParallelCodeGeneration", "false", Arg.FIXED),
    ("/Qpar", "EnableParallelCodeGeneration", "true", Arg.FIXED),
    ("/fp:except-", "FloatingPointExceptions", "false", Arg.FIXED),
    ("/fp:except", "FloatingPointExceptions", "true", Arg.FIXED),
    ("/hotpatch", "CreateHotpatchableImage", "true", Arg.FIXED),
    ("/QIntel-jcc-erratum", "IntelJCCErratum", "true", Arg.FIXED),
    ("/guard:ehcont-", "GuardEHContMetadata", "false", Arg.FIXED),
    ("/guard:ehcont", "GuardEHContMetadata", "true", Arg.FIXED),
    ("/guard:signret-", "GuardSignedReturns", "false", Arg.FIXED),
    ("/guard:signret", "GuardSignedReturns", "true", Arg.FIXED),
    ("/Za", "DisableLanguageExtensions", "true", Arg.FIXED),
    ("/Zc:wchar_t-", "TreatWChar_tAsBuiltInType", "false", Arg.FIXED),
    ("/Zc:wchar_t", "TreatWChar_tAsBuiltInType", "true", Arg.FIXED),
    ("/Zc:forScope-", "ForceConformanceInForLoopScope", "false", Arg.FIXED),
    ("/Zc:forScope", "ForceConformanceInForLoopScope", "true", Arg.FIXED),
    ("/Zc:inline-", "RemoveUnreferencedCodeData", "false", Arg.FIXED),
    ("/Zc:inline", "RemoveUnreferencedCodeData", "true", Arg.FIXED),
    ("/Zc:rvalueCast-", "EnforceTypeConversionRules", "false", Arg.FIXED),
    ("/Zc:rvalueCast", "EnforceTypeConversionRules", "true", Arg.FIXED),
    ("/GR-", "RuntimeTypeInfo", "false", Arg.FIXED),
    ("/GR", "RuntimeTypeInfo", "true", Arg.FIXED),
    ("/openmp-", "OpenMPSupport", "false", Arg.FIXED),
    ("/openmp", "OpenMPSupport", "true", Arg.FIXED),
    ("/experimental:module", "EnableModules", "true", Arg.FIXED),
    ("/Fx", "ExpandAttributedSource", "true", Arg.FIXED),
    ("/FAu", "UseUnicodeForAssemblerListing", "true", Arg.FIXED),
    ("/scanDependencies", "GenerateModuleDependencies", "true", Arg.CONTINUE),
    (
        "/sourceDependencies:directives",
        "GenerateModuleDependencies",
        "true",
        Arg.CONTINUE,
    ),
    (
        "/doc",
        "GenerateXMLDocumentationFiles",
        "true",
        Arg.VALUE | Arg.IGNORED | Arg.CONTINUE,
    ),
    ("/sourceDependencies", "GenerateSourceDependencies", "true", Arg.CONTINUE),
    ("/FR", "BrowseInformation", "true", Arg.VALUE | Arg.IGNORED | Arg.CONTINUE),
    ("/external:anglebrackets", "TreatAngleIncludeAsExternal", "true", Arg.FIXED),
    ("/external:templates-", "ExternalTemplatesDiagnostics", "true", Arg.FIXED),
    ("/analyze:external-", "DisableAnalyzeExternal", "true", Arg.FIXED),
    ("/showIncludes", "ShowIncludes", "true", Arg.FIXED),
    ("/analyze-", "EnablePREfast", "false", Arg.FIXED),
    ("/analyze", "EnablePREfast", "true", Arg.FIXED),
    ("/FC", "UseFullPaths", "true", Arg.FIXED),
    ("/Zl", "OmitDefaultLibName", "true", Arg.FIXED),
    ("/I", "AdditionalIncludeDirectories", None, Arg.VALUE | Arg.LIST),
    ("/I", "AdditionalIncludeDirectories", None, Arg.FOLLOWING | Arg.LIST),
    ("/AI", "AdditionalUsingDirectories", None, Arg.VALUE | Arg.LIST),
    ("/ifcSearchDir", "AdditionalBMIDirectories", None, Arg.VALUE | Arg.LIST),
    ("/reference", "AdditionalModuleDependencies", None, Arg.FOLLOWING | Arg.LIST),
    ("/headerUnit", "AdditionalHeaderUnitDependencies", None, Arg.FOLLOWING | Arg.LIST),
    ("/D", "PreprocessorDefinitions", None, Arg.VALUE | Arg.LIST),
    ("/D", "PreprocessorDefinitions", None, Arg.FOLLOWING | Arg.LIST),
    ("/U", "UndefinePreprocessorDefinitions", None, Arg.VALUE | Arg.LIST),
    ("/stdIfcDir", "StdIfcDirectory", None, Arg.VALUE | Arg.LIST),
    ("/external:env:", "ExternalDirectoriesEnv", None, Arg.VALUE | Arg.LIST),
    ("/wd", "DisableSpecificWarnings", None, Arg.VALUE | Arg.LIST),
    ("/FI", "ForcedIncludeFiles", None, Arg.VALUE | Arg.LIST),
    ("/FI", "ForcedIncludeFiles", None, Arg.FOLLOWING | Arg.LIST),
    ("/FU", "ForcedUsingFiles", None, Arg.VALUE | Arg.LIST),
    ("/analyze:plugin", "PREfastAdditionalPlugins", None, Arg.VALUE | Arg.LIST),
    ("/we", "TreatSpecificWarningsAsErrors", None, Arg.VALUE | Arg.LIST),
    ("/dynamicdeopt:suffix", "DynamicDebuggingSuffix", None, Arg.VALUE),
    ("/dynamicdeopt", "UseDynamicDebugging", "true", Arg.FIXED),
    ("/Wv:", "WarningVersion", None, Arg.VALUE),
    ("/Fi", "PreprocessOutputPath", None, Arg.VALUE),
    ("/Yu", "PrecompiledHeaderFile", None, Arg.VALUE),
    ("/Yc", "PrecompiledHeaderFile", None, Arg.VALUE),
    ("/Fp", "PrecompiledHeaderOutputFile", None, Arg.VALUE),
    ("/Fa", "AssemblerListingLocation", None, Arg.VALUE),
    ("/ifcOutput", "ModuleOutputFile", None, Arg.FOLLOWING),
    ("/scanDependencies", "ModuleDependenciesFile", None, Arg.FOLLOWING),
    ("/sourceDependencies:directives", "ModuleDependenciesFile", None, Arg.FOLLOWING),
    ("/Fo", "ObjectFileName", None, Arg.VALUE),
    ("/Fd", "ProgramDataBaseFileName", None, Arg.VALUE),
    ("/doc", "XMLDocumentationFileName", None, Arg.VALUE),
    ("/sourceDependencies", "SourceDependenciesFile", None, Arg.FOLLOWING),
    ("/FR", "BrowseInformationFile", None, Arg.VALUE),
    ("/analyze:log", "PREfastLog", None, Arg.FOLLOWING),
    ("/analyze:projectdirectory", "PREfastProjectDirectory", None, Arg.VALUE),
    ("/analyze:rulesetdirectory", "PREfastRulesetDirectories", None, Arg.VALUE),
    ("/analyze:ruleset", "PREfastRulesetFile", None, Arg.VALUE),
    ("/MP", "ProcessorNumber", None, Arg.VALUE),
]
LINK_SWITCHES = [
    ("/VERBOSE", "ShowProgress", "LinkVerbose", Arg.FIXED),
    ("/VERBOSE:Lib", "ShowProgress", "LinkVerboseLib", Arg.FIXED),
    ("/VERBOSE:ICF", "ShowProgress", "LinkVerboseICF", Arg.FIXED),
    ("/VERBOSE:REF", "ShowProgress", "LinkVerboseREF", Arg.FIXED),
    ("/VERBOSE:SAFESEH", "ShowProgress", "LinkVerboseSAFESEH", Arg.FIXED),
    ("/VERBOSE:CLR", "ShowProgress", "LinkVerboseCLR", Arg.FIXED),
    ("/FORCE", "ForceFileOutput", "Enabled", Arg.FIXED),
    ("/FORCE:MULTIPLE", "ForceFileOutput", "MultiplyDefinedSymbolOnly", Arg.FIXED),
    ("/FORCE:UNRESOLVED", "ForceFileOutput", "UndefinedSymbolOnly", Arg.FIXED),
    ("/FUNCTIONPADMIN", "CreateHotPatchableImage", "Enabled", Arg.FIXED),
    ("/FUNCTIONPADMIN:5", "CreateHotPatchableImage", "X86Image", Arg.FIXED),
    ("/FUNCTIONPADMIN:6", "CreateHotPatchableImage", "X64Image", Arg.FIXED),
    ("/FUNCTIONPADMIN:16", "CreateHotPatchableImage", "ItaniumImage", Arg.FIXED),
    ("/DEBUG", "GenerateDebugInformation", "true", Arg.CASE_INSENSITIVE),
    (
        "/DEBUG:FASTLINK",
        "GenerateDebugInformation",
        "DebugFastLink",
        Arg.CASE_INSENSITIVE,
    ),
    ("/DEBUG:FULL", "GenerateDebugInformation", "DebugFull", Arg.CASE_INSENSITIVE),
    ("/DEBUG:NONE", "GenerateDebugInformation", "false", Arg.CASE_INSENSITIVE),
    ("/SUBSYSTEM:CONSOLE", "SubSystem", "Console", Arg.FIXED),
    ("/SUBSYSTEM:WINDOWS", "SubSystem", "Windows", Arg.FIXED),
    ("/SUBSYSTEM:NATIVE", "SubSystem", "Native", Arg.FIXED),
    ("/SUBSYSTEM:EFI_APPLICATION", "SubSystem", "EFI Application", Arg.FIXED),
    (
        "/SUBSYSTEM:EFI_BOOT_SERVICE_DRIVER",
        "SubSystem",
        "EFI Boot Service Driver",
        Arg.FIXED,
    ),
    ("/SUBSYSTEM:EFI_ROM", "SubSystem", "EFI ROM", Arg.FIXED),
    ("/SUBSYSTEM:EFI_RUNTIME_DRIVER", "SubSystem", "EFI Runtime", Arg.FIXED),
    ("/SUBSYSTEM:POSIX", "SubSystem", "POSIX", Arg.FIXED),
    ("/Driver", "Driver", "Driver", Arg.FIXED),
    ("/DRIVER:UPONLY", "Driver", "UpOnly", Arg.FIXED),
    ("/DRIVER:WDM", "Driver", "WDM", Arg.FIXED),
    (
        "/LTCG:incremental",
        "LinkTimeCodeGeneration",
        "UseFastLinkTimeCodeGeneration",
        Arg.FIXED,
    ),
    ("/LTCG", "LinkTimeCodeGeneration", "UseLinkTimeCodeGeneration", Arg.FIXED),
    ("/LTCG:PGInstrument", "LinkTimeCodeGeneration", "PGInstrument", Arg.FIXED),
    ("/LTCG:PGOptimize", "LinkTimeCodeGeneration", "PGOptimization", Arg.FIXED),
    ("/LTCG:PGUpdate", "LinkTimeCodeGeneration", "PGUpdate", Arg.FIXED),
    ("/WINMD", "GenerateWindowsMetadata", "true", Arg.FIXED),
    ("/WINMD:NO", "GenerateWindowsMetadata", "false", Arg.FIXED),
    ("/WINMDSIGNHASH:SHA1", "WindowsMetadataSignHash", "SHA1", Arg.FIXED),
    ("/WINMDSIGNHASH:SHA256", "WindowsMetadataSignHash", "SHA256", Arg.FIXED),
    ("/WINMDSIGNHASH:SHA384", "WindowsMetadataSignHash", "SHA384", Arg.FIXED),
    ("/WINMDSIGNHASH:SHA512", "WindowsMetadataSignHash", "SHA512", Arg.FIXED),
    ("/MACHINE:ARM", "TargetMachine", "MachineARM", Arg.FIXED),
    ("/MACHINE:ARM64", "TargetMachine", "MachineARM64", Arg.FIXED),
    ("/MACHINE:ARM64EC", "TargetMachine", "MachineARM64EC", Arg.FIXED),
    ("/MACHINE:ARM64X", "TargetMachine", "MachineARM64X", Arg.FIXED),
    ("/MACHINE:EBC", "TargetMachine", "MachineEBC", Arg.FIXED),
    ("/MACHINE:IA64", "TargetMachine", "MachineIA64", Arg.FIXED),
    ("/MACHINE:MIPS", "TargetMachine", "MachineMIPS", Arg.FIXED),
    ("/MACHINE:MIPS16", "TargetMachine", "MachineMIPS16", Arg.FIXED),
    ("/MACHINE:MIPSFPU", "TargetMachine", "MachineMIPSFPU", Arg.FIXED),
    ("/MACHINE:MIPSFPU16", "TargetMachine", "MachineMIPSFPU16", Arg.FIXED),
    ("/MACHINE:SH4", "TargetMachine", "MachineSH4", Arg.FIXED),
    ("/MACHINE:THUMB", "TargetMachine", "MachineTHUMB", Arg.FIXED),
    ("/MACHINE:X64", "TargetMachine", "MachineX64", Arg.FIXED),
    ("/MACHINE:X86", "TargetMachine", "MachineX86", Arg.FIXED),
    (
        "/CLRTHREADATTRIBUTE:MTA",
        "CLRThreadAttribute",
        "MTAThreadingAttribute",
        Arg.FIXED,
    ),
    (
        "/CLRTHREADATTRIBUTE:STA",
        "CLRThreadAttribute",
        "STAThreadingAttribute",
        Arg.FIXED,
    ),
    (
        "/CLRTHREADATTRIBUTE:NONE",
        "CLRThreadAttribute",
        "DefaultThreadingAttribute",
        Arg.FIXED,
    ),
    ("/CLRIMAGETYPE:IJW", "CLRImageType", "ForceIJWImage", Arg.FIXED),
    ("/CLRIMAGETYPE:PURE", "CLRImageType", "ForcePureILImage", Arg.FIXED),
    ("/CLRIMAGETYPE:SAFE", "CLRImageType", "ForceSafeILImage", Arg.FIXED),
    ("/CLRSIGNHASH:SHA1", "SignHash", "SHA1", Arg.FIXED),
    ("/CLRSIGNHASH:SHA256", "SignHash", "SHA256", Arg.FIXED),
    ("/CLRSIGNHASH:SHA384", "SignHash", "SHA384", Arg.FIXED),
    ("/CLRSIGNHASH:SHA512", "SignHash", "SHA512", Arg.FIXED),
    ("/ERRORREPORT:PROMPT", "LinkErrorReporting", "PromptImmediately", Arg.FIXED),
    ("/ERRORREPORT:QUEUE", "LinkErrorReporting", "QueueForNextLogin", Arg.FIXED),
    ("/ERRORREPORT:SEND", "LinkErrorReporting", "SendErrorReport", Arg.FIXED),
    ("/ERRORREPORT:NONE", "LinkErrorReporting", "NoErrorReport", Arg.FIXED),
    ("/CLRSupportLastError", "CLRSupportLastError", "Enabled", Arg.FIXED),
    ("/CLRSupportLastError:NO", "CLRSupportLastError", "Disabled", Arg.FIXED),
    ("/CLRSupportLastError:SYSTEMDLL", "CLRSupportLastError", "SystemDlls", Arg.FIXED),
    ("/INCREMENTAL:NO", "LinkIncremental", "false", Arg.FIXED),
    ("/INCREMENTAL", "LinkIncremental", "true", Arg.FIXED),
    ("/NOLOGO", "SuppressStartupBanner", "true", Arg.FIXED),
    ("/LTCG:NOSTATUS", "LinkStatus", "false", Arg.FIXED),
    ("/LTCG:STATUS", "LinkStatus", "true", Arg.FIXED),
    ("/ALLOWBIND:NO", "PreventDllBinding", "false", Arg.FIXED),
    ("/ALLOWBIND", "PreventDllBinding", "true", Arg.FIXED),
    ("/WX:NO", "TreatLinkerWarningAsErrors", "false", Arg.FIXED),
    ("/WX", "TreatLinkerWarningAsErrors", "true", Arg.FIXED),
    ("/NODEFAULTLIB", "IgnoreAllDefaultLibraries", "true", Arg.FIXED),
    ("/MANIFEST:NO", "GenerateManifest", "false", Arg.FIXED),
    ("/MANIFEST", "GenerateManifest", "true", Arg.FIXED),
    ("/ALLOWISOLATION:NO", "AllowIsolation", "false", Arg.FIXED),
    ("/manifest:embed", "ManifestEmbed", "true", Arg.FIXED),
    ("/MAP", "GenerateMapFile", "true", Arg.VALUE | Arg.IGNORED | Arg.CONTINUE),
    ("/MAPINFO:EXPORTS", "MapExports", "true", Arg.FIXED),
    ("/ASSEMBLYDEBUG:DISABLE", "AssemblyDebug", "false", Arg.FIXED),
    ("/ASSEMBLYDEBUG", "AssemblyDebug", "true", Arg.FIXED),
    ("/LARGEADDRESSAWARE:NO", "LargeAddressAware", "false", Arg.FIXED),
    ("/LARGEADDRESSAWARE", "LargeAddressAware", "true", Arg.FIXED),
    ("/TSAWARE:NO", "TerminalServerAware", "false", Arg.FIXED),
    ("/TSAWARE", "TerminalServerAware", "true", Arg.FIXED),
    ("/SWAPRUN:CD", "SwapRunFromCD", "true", Arg.FIXED),
    ("/SWAPRUN:NET", "SwapRunFromNET", "true", Arg.FIXED),
    ("/OPT:NOREF", "OptimizeReferences", "false", Arg.FIXED),
    ("/OPT:REF", "OptimizeReferences", "true", Arg.FIXED),
    ("/OPT:NOICF", "EnableCOMDATFolding", "false", Arg.FIXED),
    ("/OPT:ICF", "EnableCOMDATFolding", "true", Arg.FIXED),
    ("/IGNOREIDL", "IgnoreEmbeddedIDL", "true", Arg.FIXED),
    ("/APPCONTAINER", "AppContainer", "true", Arg.FIXED),
    ("/WINMDDELAYSIGN:NO", "WindowsMetadataLinkDelaySign", "false", Arg.FIXED),
    ("/WINMDDELAYSIGN", "WindowsMetadataLinkDelaySign", "true", Arg.FIXED),
    ("/NOENTRY", "NoEntryPoint", "true", Arg.FIXED),
    ("/RELEASE", "SetChecksum", "true", Arg.FIXED),
    ("/DYNAMICBASE:NO", "RandomizedBaseAddress", "false", Arg.FIXED),
    ("/DYNAMICBASE", "RandomizedBaseAddress", "true", Arg.FIXED),
    ("/FIXED:NO", "FixedBaseAddress", "false", Arg.FIXED),
    ("/FIXED", "FixedBaseAddress", "true", Arg.FIXED),
    ("/NXCOMPAT:NO", "DataExecutionPrevention", "false", Arg.FIXED),
    ("/NXCOMPAT", "DataExecutionPrevention", "true", Arg.FIXED),
    ("/NOASSEMBLY", "TurnOffAssemblyGeneration", "true", Arg.FIXED),
    ("/DELAY:UNLOAD", "SupportUnloadOfDelayLoadedDLL", "true", Arg.FIXED),
    ("/DELAY:NOBIND", "SupportNobindOfDelayLoadedDLL", "true", Arg.FIXED),
    ("/PROFILE", "Profile", "true", Arg.FIXED),
    ("/DELAYSIGN:NO", "LinkDelaySign", "false", Arg.FIXED),
    ("/DELAYSIGN", "LinkDelaySign", "true", Arg.FIXED),
    ("/CLRUNMANAGEDCODECHECK:NO", "CLRUnmanagedCodeCheck", "false", Arg.FIXED),
    ("/CLRUNMANAGEDCODECHECK", "CLRUnmanagedCodeCheck", "true", Arg.FIXED),
    ("/ODR", "DetectOneDefinitionRule", "true", Arg.FIXED),
    ("/CETCOMPAT:NO", "CETCompat", "false", Arg.FIXED),
    ("/CETCOMPAT", "CETCompat", "true", Arg.FIXED),
    ("/SAFESEH:NO", "ImageHasSafeExceptionHandlers", "false", Arg.FIXED),
    ("/SAFESEH", "ImageHasSafeExceptionHandlers", "true", Arg.FIXED),
    ("/guard:ehcont", "LinkGuardEHContMetadata", "true", Arg.FIXED),
    ("/guard:nodelayloadsignret", "LinkGuardSignedReturns", "false", Arg.FIXED),
    ("/guard:delayloadsignret", "LinkGuardSignedReturns", "true", Arg.FIXED),
    ("/DLL", "LinkDLL", "true", Arg.FIXED),
    ("/LIBPATH:", "AdditionalLibraryDirectories", None, Arg.VALUE | Arg.LIST),
    ("/NATVIS:", "Natvis", None, Arg.VALUE | Arg.LIST),
    ("/SECTION:", "SpecifySectionAttributes", None, Arg.VALUE | Arg.LIST),
    ("/NODEFAULTLIB:", "IgnoreSpecificDefaultLibraries", None, Arg.VALUE | Arg.LIST),
    ("/ASSEMBLYMODULE:", "AddModuleNamesToAssembly", None, Arg.VALUE | Arg.LIST),
    ("/ASSEMBLYRESOURCE:", "EmbedManagedResourceFile", None, Arg.VALUE | Arg.LIST),
    ("/INCLUDE:", "ForceSymbolReferences", None, Arg.VALUE | Arg.LIST),
    ("/DELAYLOAD:", "DelayLoadDLLs", None, Arg.VALUE | Arg.LIST),
    ("/ASSEMBLYLINKRESOURCE:", "AssemblyLinkResource", None, Arg.VALUE | Arg.LIST),
    (
        "/MANIFESTDEPENDENCY:",
        "AdditionalManifestDependencies",
        None,
        Arg.VALUE | Arg.LIST,
    ),
    ("/manifestinput:", "ManifestInput", None, Arg.VALUE | Arg.LIST),
    ("/OUT:", "OutputFile", None, Arg.VALUE),
    ("/VERSION:", "Version", None, Arg.VALUE),
    ("/ILK:", "IncrementalLinkDatabaseFile", None, Arg.VALUE),
    ("/STUB:", "MSDOSStubFileName", None, Arg.VALUE),
    ("/DEF:", "ModuleDefinitionFile", None, Arg.VALUE),
    ("/ManifestFile:", "ManifestFile", None, Arg.VALUE),
    ("/PDB:", "ProgramDatabaseFile", None, Arg.VALUE),
    ("/PDBSTRIPPED:", "StripPrivateSymbols", None, Arg.VALUE),
    ("/MAP:", "MapFileName", None, Arg.VALUE),
    ("/dynamicdeopt:suffix=", "DynamicDebuggingSuffix", None, Arg.VALUE),
    ("/dynamicdeopt", "UseDynamicDebugging", "true", Arg.FIXED),
    ("/HEAP:", "HeapReserveSize", None, Arg.VALUE),
    ("/HEAP", "HeapCommitSize", None, Arg.VALUE),
    ("/STACK:", "StackReserveSize", None, Arg.VALUE),
    ("/STACK", "StackCommitSize", None, Arg.VALUE),
    ("/ORDER:@", "FunctionOrder", None, Arg.VALUE),
    ("/PGD:", "ProfileGuidedDatabase", None, Arg.VALUE),
    ("/LTCGOUT:", "LinkTimeCodeGenerationObjectFile", None, Arg.VALUE),
    ("/MIDL:@", "MidlCommandFile", None, Arg.VALUE),
    ("/IDLOUT:", "MergedIDLBaseFileName", None, Arg.VALUE),
    ("/TLBOUT:", "TypeLibraryFile", None, Arg.VALUE),
    ("/WINMDFILE:", "WindowsMetadataFile", None, Arg.VALUE),
    ("/WINMDKEYFILE:", "WindowsMetadataLinkKeyFile", None, Arg.VALUE),
    ("/WINMDKEYCONTAINER:", "WindowsMetadataKeyContainer", None, Arg.VALUE),
    ("/ENTRY:", "EntryPointSymbol", None, Arg.VALUE),
    ("/BASE:", "BaseAddress", None, Arg.VALUE),
    ("/IMPLIB:", "ImportLibrary", None, Arg.VALUE),
    ("/KEYFILE:", "LinkKeyFile", None, Arg.VALUE),
    ("/KEYCONTAINER:", "KeyContainer", None, Arg.VALUE),
    ("/TLBID:", "TypeLibraryResourceID", None, Arg.VALUE),
    ("/ALIGN:", "SectionAlignment", None, Arg.VALUE),
    ("/pdbthreads:", "PdbThreads", None, Arg.VALUE),
    ("/cgthreads:", "CgThreads", None, Arg.VALUE),
]
TOOLSET_SWITCHES = {
    ("/arch:AVX10.1", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:AVX10.2", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:ARMv7VE", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:VFPv4", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:armv8.0", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:armv8.1", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:armv8.2", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:armv8.3", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:armv8.4", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:armv8.5", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:armv8.6", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:armv8.7", "EnableEnhancedInstructionSet"): {"v145"},
    ("/arch:armv8.8", "EnableEnhancedInstructionSet"): {"v145"},
    ("/vlen=256", "EnableVectorLength"): {"v145"},
    ("/vlen=512", "EnableVectorLength"): {"v145"},
    ("/scanDependencies", "GenerateModuleDependencies"): {"v145"},
    ("/dynamicdeopt:suffix", "DynamicDebuggingSuffix"): {"v145"},
    ("/dynamicdeopt", "UseDynamicDebugging"): {"v145"},
    ("/MACHINE:IA64", "TargetMachine"): {"v143"},
    ("/MACHINE:MIPS", "TargetMachine"): {"v143"},
    ("/MACHINE:MIPS16", "TargetMachine"): {"v143"},
    ("/MACHINE:MIPSFPU", "TargetMachine"): {"v143"},
    ("/MACHINE:MIPSFPU16", "TargetMachine"): {"v143"},
    ("/MACHINE:SH4", "TargetMachine"): {"v143"},
    ("/MACHINE:THUMB", "TargetMachine"): {"v143"},
    ("/dynamicdeopt:suffix=", "DynamicDebuggingSuffix"): {"v145"},
}

# Default compiler settings, these override msbuild defaults either because the
# flag lacks disable flags (can turn on but not off), or to otherwise provide
# sensible defaults...
DEFAULT_COMPILE_SETTINGS = {
    # These lack explicit disable flags...
    "WholeProgramOptimization": "false",
    "DebugInformationFormat": "None",
    "BasicRuntimeChecks": "Default",
    "ExceptionHandling": "false",
    # Just sensible defaults...
    "MultiProcessorCompilation": "true",
}

# Default linker settings, because some options have no explicit disable flag...
DEFAULT_LINK_SETTINGS = {
    "GenerateDebugInformation": "false",
}

# Link properties MSBuild reads as project properties rather than Link metadata
PROJECT_LINK_PROPERTIES = {"LinkIncremental", "GenerateManifest", "LinkDelaySign"}

DEBUG_RUNTIME_LIBRARIES = {"MultiThreadedDebug", "MultiThreadedDebugDLL"}


def switches_for(switches: List[Switch], toolset: str) -> List[Switch]:
    return [s for s in switches if toolset in TOOLSET_SWITCHES.get(s[:2], {toolset})]


# Set the property of each recognized flag and return the other flags in order.
def map_flags(
    properties: Dict[str, str], flags: List[str], switches: List[Switch]
) -> List[str]:
    remaining: List[str] = []
    i = 0
    while i < len(flags):
        flag = flags[i]
        i += 1
        name = "/" + flag[1:] if flag.startswith("-") else flag
        matched = False
        for switch, prop, value, arg in switches:
            if arg & Arg.FOLLOWING:
                if name != switch or i >= len(flags):
                    continue
                user = flags[i]
                i += 1
            elif arg & Arg.VALUE:
                if not name.startswith(switch):
                    continue
                user = name[len(switch) :]
                if not user and not arg & Arg.IGNORED:
                    continue
            elif name == switch or (
                arg & Arg.CASE_INSENSITIVE and name.upper() == switch.upper()
            ):
                user = ""
            else:
                continue
            new = user if value is None else value
            if arg & Arg.LIST and properties.get(prop):
                new = f"{properties[prop]};{new}"
            properties[prop] = new
            matched = True
            if not arg & Arg.CONTINUE:
                break
        if not matched:
            remaining.append(flag)
    return remaining
